@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYWRtaW4iLCJleHAiOjE3ODI5MDk0ODV9.6bKFbHhnXCtkhdoks0xyeLm_MLxFY3gnnGhRhSiHrzM

###

GET http://localhost:5000/


###

POST http://127.0.0.1:5000/login
content-type: application/json

{
    "username": "admin",
    "password": "supersecret"
}

###

GET http://127.0.0.1:5000/products
Authorization: Bearer {{token}}
content-type: application/json



### 
GET http://127.0.0.1:5000/products/6a44fc6dc9fd53ef0d8fcd40
Authorization: Bearer {{token}}
content-type: application/json

### 

POST http://127.0.0.1:5000/products
Authorization: Bearer {{token}}
content-type: application/json

{
"name": "Notebook Gamer Pro X15",
"price": 9500.50,
"description":"Notebook de alta performance com 32GB de RAM, SSD de 1TB e placa de vídeo dedicada de 8GB.",
"stock": 15
}


###

POST http://127.0.0.1:5000/products
Authorization: Bearer {{token}}
content-type: application/json

{
"name": "Produto para exclusão",
"price": 10.00,
"description":"Produto que será excluído em breve.",
"stock": 4
}

###

PUT http://127.0.0.1:5000/products/6a44fc6dc9fd53ef0d8fcd40
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Notebook Gamer Pro X15"
}   

###

DELETE http://127.0.0.1:5000/products/6a4503b8047be8874058c177
Authorization: Bearer {{token}}
Content-Type: application/json

